# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20170331_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(null=True, upload_to='author_photo/'),
        ),
    ]
